name: Run tests on push

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Set up
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello"
      - name: list versions
        run: |
            node -v
            npm -v
      - name: clone repo into the vm
        uses: actions/checkout@v2

      - name: set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: set up node 12
        uses: actions/setup-node@v3
        with:
          node-version: 12
      
      # - name: install deps
      #   run: npm install

      - name: print time
        run: TZ="America/Montreal" node -e "console.log(Date(Date.now()).toString())"

      - name: print time withouth TZ
        run: node -e "console.log(Date(Date.now()).toString())"
